### ISSUE TITLE
Any plans to release caffemodel and proto?

### ISSUE THREAD

**Issue by kizilkanat** [LouieYang/caf_face_detection#1]
Hi,
do you have plans to release the caffemodel and proto file?

**Comment by LouieYang** [comment]
@kkirtac Just visit https://github.com/guoyilin/FaceDetection_CNN. 
btw, it's not my work, I just translate it from python to Cpp to learn caffe

**Comment by LouieYang** [comment]
I close this issue since both caffemodel and photo file can be found in the url above. Also, thanks guoyilin for amazing python job
