### ISSUE TITLE
OpenCV2Blob...

### ISSUE THREAD

**Issue by rap9430** [LouieYang/caf_face_detection#2]
Hi!

Is the body of the function OpenCV2Blob missing?

**Comment by LouieYang** [comment]
I was intending to translate OpenCV Mat to Caffe Blob directly, but failed because I wasn't quite familiar with OpenCV Mat operation. Instead, I use Eigen MatrixX as a transition and the OpenCV2Blob is abandoned.

Yeah, I will try to restore this repo in following days. Thanks to the question

**Comment by LouieYang** [comment]
I have update OpenCV2Blob and no more transition from OpenCV -> Eigen -> Blob. Close this issue.
